server.port: 5555

app.mynameis: http://localhost:5556/myNameIs

trackia.dispatcher.class: trackiaServerDispatcher
trackia.dispatcher.url: https://trackiaapp.com/journal
trackia.dispatcher.auth: https://trackiaapp.com/auth/signin

trackia.dispatcher.account: <Account ID>
trackia.dispatcher.apiKey: <Artefact ApiKey>
